version: "3.8"

services:
  prod:
    build:
      context: .
      # dockerfile: .devcontainer/Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./workspace:/root/workspace
    working_dir: /root/workspace
    # command: ["tail", "-f", "/dev/null"]
    command:
      ["uvicorn", "main:app", "--host", "0.0.0.0", 
        "--port", "443", "--reload", 
        "--ssl-keyfile", "key.pem", "--ssl-certfile", "cert.pem"]
    restart: unless-stopped